protocol = "omega-platinum"
doc = ""
traits = ["is-daemon", "is-sensor", "uses-serial", "uses-uart", "has-measure-trigger"]
hardware = ["omega:dp32pt", "omega:dp16pt", "omega:dp8pt"]

[links]
source = "https://github.com/yaq-project/yaqd-omega"
bugtracker = "https://github.com/yaq-project/yaqd-omega/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-omega"

[config]

[config.units]
doc = "Units string. If not specified, will attempt to pull units off of hardware."
type=["null", "string"]
default = "__null__"

[state]

[messages]
